const express = require('express')
const app = express()
app.use(express.json())
app.use(express.urlencoded({ extended: false }))
require('dotenv').config()
const connect = require('./config/db.config')
const personRoutes = require('./models/person/routes/person.route')
const postRoutes = require('./models/post/routes/post.route')
const reportRoutes = require('./models/report/routes/report.route')
const advertisementRoutes = require('./models/advertisement/routes/advertisement.route')
connect()

app.use(personRoutes)
app.use(postRoutes)
app.use(reportRoutes)
app.use(advertisementRoutes)
app.get('/', (req, res) => res.send('Hello World!'))
app.listen(process.env.PORT, () => console.log(`Example app listening on port ${process.env.PORT}!`))
