const ADD_PERSON = "person:ADD_PERSON";
const SIGNIN = "person:ADMIN_SIGNIN";
const UPDATE_PERSON = "person:UPDATE_PERSON";
const DELETE_PERSON = "person:DELETE_PERSON";
const UPDATE_PASSWORD = "person:UPDATE_PASSWORD";
const UPDATE_DEACTIVED = "person:UPDATE_DEACTIVED";
const ADD_ADMIN = "person:ADD_ADMIN";
const GET_ALL_USER = "person:GET_ALL_USER";
const GET_ALL_ADMIN = "person:GET_ALL_ADMIN";


const ADD_POST = "post:ADD_POST";
const UPDATE_POST = "post:UPDATE_POST";
const DELETE_POST = "post:DELETE_POST";
const GET_USER_POST = "post:GET_USER_POST";
const NEWS_FEED = "post:NEWS_FEED";
const GET_ALL_POST = "post:GET_ALL_POST";
const BLOCK_POST = "post:BLOCK_POST";


const USER_REPORTING = "advertisement:USER_REPORTING";
const GET_ALL_REPORTING = "advertisement:GET_ALL_REPORTING";

const ADD_ADVERTISEMENT = "advertisement:ADD_ADVERTISEMENT";
const GET_ADVERTISEMENT = "advertisement:GET_ADVERTISEMENT";
const UPDATE_ADVERTISEMENT = "advertisement:UPDATE_ADVERTISEMENT";
const DELETE_ADVERTISEMENT = "advertisement:DELETE_ADVERTISEMENT";

module.exports = {
    ADD_PERSON,
    SIGNIN,
    UPDATE_PERSON,
    DELETE_PERSON,
    UPDATE_PASSWORD,
    UPDATE_DEACTIVED,
    ADD_ADMIN,
    GET_ALL_USER,
    GET_ALL_ADMIN,
    ADD_POST,
    UPDATE_POST,
    DELETE_POST,
    GET_USER_POST,
    NEWS_FEED,
    GET_ALL_POST,
    BLOCK_POST,
    USER_REPORTING,
    GET_ALL_REPORTING,
    ADD_ADVERTISEMENT,
    GET_ADVERTISEMENT,
    UPDATE_ADVERTISEMENT,
    DELETE_ADVERTISEMENT,
}